CREATE ROLE voxera_app LOGIN PASSWORD 'voxera-app-local' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT CONNECT ON DATABASE voxera TO voxera_app;
GRANT USAGE ON SCHEMA public TO voxera_app;

ALTER DEFAULT PRIVILEGES FOR ROLE voxera_admin IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO voxera_app;

ALTER DEFAULT PRIVILEGES FOR ROLE voxera_admin IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO voxera_app;

